name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request: # Runs on pull requests targeting any branch

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' # Should match the version in go.mod

      - name: Verify formatting
        run: |
          gofmt_output=$(gofmt -l .)
          if [ -n "$gofmt_output" ]; then
            echo "Go code is not formatted correctly. Please run 'gofmt -w .'"
            echo "Files needing formatting:"
            echo "$gofmt_output"
            exit 1
          fi
          echo "Go code formatting is correct."

      - name: Vet code
        run: go vet ./...

      - name: Run tests
        run: go test -v -race ./...
